apps/shop/urls.py
from django.urls import path, include

from apps.shop.views import (
    products_list,
    product_detail,
    category_products,
    search_results_view,
    cart_page,
    checkout_page,
    checkout_success_page,
    add_to_cart,
    update_cart,
    clear_cart,

    cart_api,
)


# app_name = 'products'

urlpatterns = [
    path('products/', include(([
        path('', products_list, name='list'),
        path('<int:id>/', product_detail, name='detail'),
    ], 'products'), namespace='products')),


    path('category/', include(([
        path('<slug:slug>/', category_products, name='slug'),
    ], 'category'), namespace='category')),


    path('search-results/', include(([
        path('', search_results_view, name='results'),
    ], 'search'), namespace='search')),


    # Cart
    path('cart/', include(([
        path('', cart_page, name='page'),
        path('checkout/', checkout_page, name='checkout'),
        path('checkout-success/', checkout_success_page, name='checkout-success'),
        path('add/', add_to_cart, name='add'),
        path('update/', update_cart, name='update'),
        path('clear-cart/', clear_cart, name='clear'),

        path('api/', cart_api, name='api'),
    ], 'cart'), namespace='cart')),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.core.urls')),
    path('', include('apps.pages.urls')),
    path('', include('apps.shop.urls')),
]


# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'apps.core.views.error_404'

apps/shop/models.py
from django.db import models
from django.urls import reverse
from django.utils.html import mark_safe

from django.db.models.signals import pre_save, post_save, post_delete
from django.dispatch import receiver

from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill, ResizeToFit


class Categories(models.Model):
    name = models.CharField('Название категории', max_length=255)
    slug = models.SlugField('URL категории', max_length=100, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category:slug', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории товаров'


def main_image_upload_path(instance, filename):
    return f'products/{instance.sku}/{filename.lower()}'

class Products(models.Model):
    active         = models.BooleanField('Активный', default=True, help_text='Опубликован ли товар?')
    sku            = models.CharField('Артикул', max_length=50)
    name           = models.CharField('Название товара', max_length=255)
    categories     = models.ManyToManyField(Categories, verbose_name='Категории товара')
    price_discount = models.DecimalField('Цена без скидки', max_digits=8, decimal_places=2, blank=True, null=True)
    price          = models.DecimalField('Цена', max_digits=8, decimal_places=2)
    body           = models.TextField('Описание товара', blank=True, null=True)
    # main_image     = models.ImageField('Главное изображение', upload_to=main_image_upload_path, blank=True, null=True)
    main_image     = ProcessedImageField(verbose_name='Главное изображение',
                                        upload_to=main_image_upload_path,
                                        processors=[ResizeToFit(1920, 1080)],
                                        format='JPEG',
                                        options={'quality': 75},
                                        blank=True, null=True)

    main_image_thumbnail = ImageSpecField(source='main_image',
                                        # processors=[ResizeToFill(512, 512)],
                                        processors=[ResizeToFit(512, 512)],
                                        format='JPEG',
                                        options={'quality': 70})

    updated        = models.DateTimeField(auto_now=True, auto_now_add=False)

    # Thumbnail for admin
    def main_image_thumb(self):
        return mark_safe(f'<img style="width: 512px; height: auto;" src="{self.main_image.url}" alt="">')
    main_image_thumb.short_description = 'Главное изображение (thumb)'
    # END Thumbnail for admin

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


def product_image_upload_path(instance, filename):
    return f'products/{instance.product.sku}/{filename.lower()}'

class ProductsImages(models.Model):
    product = models.ForeignKey(Products, verbose_name='Товар', on_delete=models.CASCADE)
    image   = ProcessedImageField(verbose_name='Изображение',
                                upload_to=product_image_upload_path,
                                processors=[ResizeToFit(1920, 1080)],
                                format='JPEG',
                                options={'quality': 75},
                                blank=True, null=True)

    image_thumbnail = ImageSpecField(source='image',
                                    processors=[ResizeToFill(128, 100)],
                                    format='JPEG',
                                    options={'quality': 70})

    # Thumbnail for admin
    def image_thumb(self):
        return mark_safe(f'<img style="width: 386px; height: auto;" src="{self.image.url}" alt="">')
    image_thumb.short_description = 'Изображение (thumb)'
    # END Thumbnail for admin

    def __str__(self):
        return self.product.name

    class Meta:
        verbose_name = 'Изображение товара'
        verbose_name_plural = 'Изображения товаров'



# @receiver(post_save, sender=Categories)
# def lowercase_category_slug(sender, instance, created, **kwargs):
@receiver(pre_save, sender=Categories)
def lowercase_category_slug(sender, instance, **kwargs):
    instance.slug = instance.slug.lower()

apps/shop/forms.py
from django import forms


class CheckoutForm(forms.Form):
    fio      = forms.CharField(max_length=255, help_text='Укажите вашу Фамилию, Имя и Отчество')
    zip_code = forms.CharField(max_length=50, help_text="<a href=\"https://pochta.ru/post-index\" target=\"_blank\">Найти свой индекс</a>")
    address  = forms.CharField(max_length=255, help_text='Город, улица, дом, квартира')
    phone    = forms.CharField(max_length=100, help_text='Укажите в формате: +7 999 000-00-00')
    email    = forms.EmailField(max_length=200, help_text='Укажите ваш действующий email')
    message  = forms.CharField(widget=forms.Textarea,
                                max_length=1000,
                                required=False,
                                help_text='Укажите комментарий или примечание к вашему заказу')

apps/shop/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.http import JsonResponse

# from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string

from .models import Categories, Products, ProductsImages
from .forms import CheckoutForm


def products_list(request):
    products = Products.objects.filter(active=True).order_by('-updated')

    # Filters
    filter_price = request.GET.get('price')
    filter_category = request.GET.get('category')

    if filter_price and filter_price == 'asc':
        products = products.order_by('price')

    if filter_price and filter_price == 'desc':
        products = products.order_by('-price')

    if filter_category and filter_category != '':
        products = products.filter(categories__slug=filter_category)
    # END Filters

    # Pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(products, 6)
    # paginator = Paginator(products, 1)

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    # END Pagination

    context = {
        'page_title': 'Каталог товаров',
        # 'page_description': 'Описание каталога',
        'products': products,
        'categories': Categories.objects.all(),
    }
    return render(request, 'shop/products_list.html', context=context)


def product_detail(request, id):
    product = Products.objects.filter(active=True).get(id=id)
    context = {
        'page_title': product.name,
        'product': product,
        'product_images': ProductsImages.objects.filter(product=product.pk),
        'other_products': Products.objects.filter(active=True).exclude(id=product.pk).order_by('?')[:6],
    }
    return render(request, 'shop/product_detail.html', context=context)


def category_products(request, slug):
    products = Products.objects.filter(active=True, categories__slug=slug).order_by('-updated')

    # Pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(products, 6)
    # paginator = Paginator(products, 1)

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    # END Pagination

    context = {
        'page_title': Categories.objects.get(slug=slug).name,
        'products': products,
    }
    return render(request, 'shop/category_products.html', context=context)


def search_results_view(request):
    search_query = request.GET.get('q')

    if search_query:
        products = Products.objects.filter(active=True, name__icontains=search_query)
        products_count = str(products.count())

        # Pagination
        page = request.GET.get('page', 1)
        paginator = Paginator(products, 6)

        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)
        # END Pagination

        context = {
            'page_title': 'Результаты поиска: ' + search_query,
            'page_description': 'найдено ' + products_count + ' результатов',
            'products': products,
        }
        return render(request, 'shop/serch_results.html', context=context)

    if not search_query:
        return redirect('/products/')


def cart_page(request):
    context = {
        'page_title': 'Корзина',
    }
    return render(request, 'shop/cart_page.html', context=context)


def checkout_page(request):
    form = CheckoutForm()

    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            # print(form.cleaned_data['fio'])
            # print(form.cleaned_data['zip_code'])
            # print(form.cleaned_data['address'])
            # print(form.cleaned_data['phone'])
            # print(form.cleaned_data['email'])
            # print(form.cleaned_data['message'])

            # Send Order email from template
            total_qty = total_price = 0

            # Calculate totals
            for item in request.session.get('cart'):
                total_qty += item['qty']
                total_price += item['price']

            context_data = {
                'fio': form.cleaned_data['fio'],
                'zip_code': form.cleaned_data['zip_code'],
                'address': form.cleaned_data['address'],
                'phone': form.cleaned_data['phone'],
                'email': form.cleaned_data['email'],
                'message': form.cleaned_data['message'],
                'cart_items': request.session.get('cart'),
                'total_qty': total_qty,
                'total_price': total_price,
            }

            html_body = render_to_string("email_templates/order.html", context_data)
            msg = EmailMultiAlternatives(subject='Ваш заказ', from_email='beautyroom37@mail.ru', to=['beautyroom37@mail.ru',])
            msg.attach_alternative(html_body, "text/html")
            msg.send()

            if request.session.get('cart'):
                del request.session['cart']
                request.session.modified = True
                return redirect('/cart/checkout-success/')

            return redirect('/cart/checkout/')

    context = {
        'page_title': 'Оформление заказа',
        'form': form,
    }
    return render(request, 'shop/checkout_page.html', context=context)


def checkout_success_page(request):
    context = {
        'page_title': 'Ваш заказ успешно оформлен!',
    }
    return render(request, 'shop/checkout_success_page.html', context=context)


def add_to_cart(request):
    if request.method == 'POST':
        # check if session cart not exist
        if not request.session.get('cart'):
            request.session['cart'] = list()

        data = {
            'sku': request.POST.get('product_sku'),
            'name': request.POST.get('product_name'),
            'price': float(request.POST.get('product_price').replace(',', '.')),
            'qty': int(request.POST.get('product_qty')),
        }

        product_in_cart = False

        # check if product alredy in cart
        if not any(d['sku'] == request.POST.get('product_sku') for d in request.session['cart']):
            product_in_cart = True
            request.session['cart'].append(data)
            request.session.modified = True

    # If is AJAX
    if request.is_ajax():
        return JsonResponse({'product_in_cart': product_in_cart})

    return redirect(request.POST.get('url_from'))


def cart_api(request):
    cart_session = request.session.get('cart')
    if cart_session:
        return JsonResponse(cart_session, safe=False)
    else:
        return JsonResponse({'cart_session': 'is not exist'})


def delete_empty_cart(request):
    if len(request.session['cart']) == 0:
        del request.session['cart']
        request.session.modified = True


# remove empty {} from cart list
def remove_empty_dicts_from_cart(request):
    while {} in request.session['cart']:
        request.session['cart'].remove({})
        request.session.modified = True


def update_cart(request):
    if request.method == 'POST':
        # Remove product from cart
        if request.POST.get('remove-item'):
            for item in request.session['cart']:
                if item['sku'] == request.POST.get('remove-item'):
                    item.clear()
                    request.session.modified = True

                    remove_empty_dicts_from_cart(request)
                    delete_empty_cart(request)

            # if cart has any products, redirect to /cart/ route
            if request.session.get('cart'):
                return redirect('/cart/')

            # if cart session is not exist, redirect to /products/
            if not request.session.get('cart'):
                return redirect('/products/')
        # Go to checkout page
        if request.POST.get('checkout'):
            return redirect('/cart/checkout/')


def clear_cart(request):
    if request.method == 'POST':
        if request.session.get('cart'):
            del request.session['cart']
            request.session.modified = True
    return redirect('/products/')

templates/shop/includes/add-to-cart.html
{% load shop_tags %}
<form class="add-to-cart-form" action="{% url 'cart:add' %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="product_sku" value="{{ product_sku }}">
    <input type="hidden" name="product_name" value="{{ product_name }}">
    <input type="hidden" name="product_price" value="{{ product_price }}">
    <input type="hidden" name="product_qty" value="{{ product_qty }}">
    <input type="hidden" name="url_from" value="{{ request.path }}">

    {# <!-- {% product_in_cart request=request product_sku=product_sku as in_cart %} --> #}

    <div class="in-cart-wrap">
        {% comment %}<!-- <button type="submit" class="yet-not-in-cart btn btn-success">
            <i class="fas fa-cart-plus"></i> В корзину
        </button> -->
        <!-- {% if not in_cart %}
            <button type="submit" class="yet-not-in-cart btn btn-success">
                <i class="fas fa-cart-plus"></i> В корзину
            </button>
        {% else %}
            <button class="alredy-in-cart btn btn-secondary" disabled>
                <i class="fas fa-check"></i> Товар в корзине
            </button>
        {% endif %} -->{% endcomment %}
    </div>
</form>

templates/shop/includes/filters-products.html
<div class="container mb-4">
    {{ request.GET.price }}
    {{ request.GET.category }}

    <form action="" autocomplete="off" method="get">
        <div class="form-row align-items-end">
            {% comment %}
            <!--
                TODO:
                    - phone model
                    - discount
            -->
            {% endcomment %}
            <div class="form-group col-lg-2">
                <label for="filter-select-categories">Цена</label>
                <select id="filter-select-categories" class="form-control" name="price">
                    <option {% if request.GET.price == '' or not request.GET.price %}selected{% endif %} disabled>Сортировать по...</option>
                    <option {% if request.GET.price == 'asc' %}selected{% endif %} value="asc">Возрастанию</option>
                    <option {% if request.GET.price == 'desc' %}selected{% endif %} value="desc">Убыванию</option>
                </select>
            </div>
            <div class="form-group col-lg-2">
                <label for="filter-select-categories">Категория</label>
                <select id="filter-select-categories" class="form-control" name="category">
                    <option {% if not request.GET.category %}selected{% endif %} value="">Все категори</option>
                    {% for category in categories %}
                        <option {% if request.GET.category == category.slug %}selected{% endif %} value="{{ category.slug }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group col-lg-3 text-right text-lg-left">
                <a href="{% url 'products:list' %}" class="btn btn-outline-secondary mr-2">Сбросить</a>
                <button type="submit" class="btn btn-primary">Сортировать</button>
            </div>
        </div>
    </form>
</div>

templates/shop/includes/pagination-search.html
{% if products.has_other_pages %}
    <div class="container">
        <nav class="mt-4">
            <ul class="pagination justify-content-center">
                <li class="page-item">
                    <a class="page-link" href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Начало</a>
                </li>
                {% if products.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ products.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&lt;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&lt;</a>
                    </li>
                {% endif %}

                {% if products.number|add:'-4' > 1 %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ products.number|add:'-5' }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&hellip;</a>
                    </li>
                {% endif %}

                {% for i in products.paginator.page_range %}
                    {% if products.number == i %}
                        <li class="page-item active">
                            <a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a>
                        </li>
                    {% elif i > products.number|add:'-5' and i < products.number|add:'5' %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if products.paginator.num_pages > products.number|add:'4' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ products.number|add:'5' }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&hellip;</a>
                    </li>
                {% endif %}

                {% if products.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ products.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&gt;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&gt;</a>
                    </li>
                {% endif %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ products.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Последняя</a>
                </li>
            </ul>
        </nav>
    </div>
{% endif %}

templates/shop/includes/pagination.html
{% if products.has_other_pages %}
    <div class="container">
        <nav class="mt-4">
            <ul class="pagination justify-content-center">
                <li class="page-item">
                    <a class="page-link" href="?page=1{% if request.GET.price %}&price={{ request.GET.price }}{% endif %}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">Начало</a>
                </li>
                {% if products.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ products.previous_page_number }}{% if request.GET.price %}&price={{ request.GET.price }}{% endif %}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">&lt;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&lt;</a>
                    </li>
                {% endif %}

                {% if products.number|add:'-4' > 1 %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ products.number|add:'-5' }}{% if request.GET.price %}&price={{ request.GET.price }}{% endif %}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">&hellip;</a>
                    </li>
                {% endif %}

                {% for i in products.paginator.page_range %}
                    {% if products.number == i %}
                        <li class="page-item active">
                            <a class="page-link" href="?page={{ i }}{% if request.GET.price %}&price={{ request.GET.price }}{% endif %}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">{{ i }}</a>
                        </li>
                    {% elif i > products.number|add:'-5' and i < products.number|add:'5' %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}{% if request.GET.price %}&price={{ request.GET.price }}{% endif %}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if products.paginator.num_pages > products.number|add:'4' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ products.number|add:'5' }}{% if request.GET.price %}&price={{ request.GET.price }}{% endif %}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">&hellip;</a>
                    </li>
                {% endif %}

                {% if products.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ products.next_page_number }}{% if request.GET.price %}&price={{ request.GET.price }}{% endif %}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">&gt;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&gt;</a>
                    </li>
                {% endif %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ products.paginator.num_pages }}{% if request.GET.price %}&price={{ request.GET.price }}{% endif %}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">Последняя</a>
                </li>
            </ul>
        </nav>
    </div>
{% endif %}

templates/shop/includes/search_section.html
<div class="container mb-5">
    <form action="{% url 'search:results' %}" autocomplete="off" method="get">
        <div class="input-group">
            <input type="search" class="form-control" name="q" placeholder="Поиск по каталогу"{% if request.GET.q %} value="{{ request.GET.q }}"{% endif %} aria-label="Поиск по каталогу" aria-describedby="search-button">
            <div class="input-group-append">
                <button class="btn btn-outline-success" type="submit" id="search-button">
                    <i class="fas fa-search"></i> Найти
                </button>
            </div>
        </div>
    </form>
</div>

templates/shop/includes/total-cart.html
{% if cart_total_qty != 0 %}
    <div class="row">
        <div class="col-0 offset-lg-9"></div>
        <div class="col-12 col-lg-3 text-center text-lg-right">
            <div class="py-3 border-top border-bottom">
                <div class="h4">Итого:</div>
                <div>
                    <span class="font-weight-bold">Всего товаров:</span> {{ cart_total_qty }} шт
                </div>
                <div>
                    <span class="font-weight-bold">На сумму:</span> {{ cart_total_price|floatformat:"-2" }} руб
                </div>
            </div>
        </div>
    </div>
{% endif %}