apps/shop/urls.py
from django.urls import path, include

from apps.shop.views import (
    products_list,
    product_detail,
    category_products,
    search_results_view,
    cart_page,
    checkout_page,
    checkout_success_page,
    add_to_cart,
    update_cart,
    clear_cart,

    cart_api,
)


# app_name = 'products'

urlpatterns = [
    path('products/', include(([
        path('', products_list, name='list'),
        path('<int:id>/', product_detail, name='detail'),
    ], 'products'), namespace='products')),


    path('category/', include(([
        path('<slug:slug>/', category_products, name='slug'),
    ], 'category'), namespace='category')),


    path('search-results/', include(([
        path('', search_results_view, name='results'),
    ], 'search'), namespace='search')),


    # Cart
    path('cart/', include(([
        path('', cart_page, name='page'),
        path('checkout/', checkout_page, name='checkout'),
        path('checkout-success/', checkout_success_page, name='checkout-success'),
        path('add/', add_to_cart, name='add'),
        path('update/', update_cart, name='update'),
        path('clear-cart/', clear_cart, name='clear'),

        path('api/', cart_api, name='api'),
    ], 'cart'), namespace='cart')),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.core.urls')),
    path('', include('apps.pages.urls')),
    path('', include('apps.shop.urls')),
]


# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'apps.core.views.error_404'

templates/includes/favicons.html
{% load static %}<link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicons/apple-icon-57x57.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicons/apple-icon-60x60.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicons/apple-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicons/apple-icon-76x76.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicons/apple-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicons/apple-icon-120x120.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicons/apple-icon-144x144.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicons/apple-icon-152x152.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicons/apple-icon-180x180.png' %}">
<link rel="icon" type="image/png" sizes="192x192" href="{% static 'favicons/android-icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicons/favicons-32x32.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicons/favicons-96x96.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicons/favicons-16x16.png' %}">
<link rel="manifest" href="{% static 'favicons/manifest.json' %}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{% static 'favicons/ms-icon-144x144.png' %}">
<meta name="theme-color" content="#ffffff">

templates/includes/main-nav.html
{# <!-- <nav id="main-nav" class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark"> --> #}
<nav id="main-nav" class="navbar fixed-top navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="{% url 'homepage' %}">Casekam</a>
    <span class="navbar-text d-none d-sm-inline-block d-lg-none d-xl-inline-block">Чехлы для смартфонов</span>

    <div class="d-inline-block d-sm-none">
        <a id="cart-link_xs" class="nav-link" href="{% url 'cart:page' %}">
            <i class="fas fa-shopping-cart"></i> <span class="badge badge-secondary">{{ cart_qty }}</span>
        </a>
    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapsedContent" aria-controls="navbarCollapsedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapsedContent">
        <ul class="navbar-nav ml-auto">
            {% url 'homepage' as homepage_url %}
            {% if homepage_url != request.path %}
                <li class="nav-item{% if homepage_url == request.path %} active{% endif %}">
                    <a class="nav-link" href="{{ homepage_url }}">Главная</a>
                </li>
            {% endif %}

            {% url 'products:list' as products_list_url %}
            <li class="nav-item{% if products_list_url == request.path or products_list_url in request.path %} active{% endif %}">
                <a class="nav-link" href="{{ products_list_url }}">Каталог товаров</a>
            </li>

            {% url 'page-detail' slug='shipmet-payment' as page_shipment_payment_url %}
            <li class="nav-item{% if page_shipment_payment_url == request.path %} active{% endif %}">
                <a class="nav-link" href="{{ page_shipment_payment_url }}">Доставка и оплата</a>
            </li>

            {% url 'page-detail' slug='contacts' as page_contacts_url %}
            <li class="nav-item{% if page_contacts_url == request.path %} active{% endif %}">
                <a class="nav-link" href="{{ page_contacts_url }}">Контакты</a>
            </li>
        </ul>
        <ul class="ml-0 ml-lg-3 navbar-nav">
            <li class="nav-item">
                {% comment %}<!-- <a class="nav-link"{% if cart_qty > 0 %} href="{% url 'cart:page' %}"{% else %} style="cursor: default;"{% endif %}>
                    <i class="fas fa-shopping-cart"></i> Корзина <span class="badge badge-{% if cart_qty > 0 %}warning{% else %}secondary{% endif %}">{{ cart_qty }}</span>
                </a> -->{% endcomment %}
                <a id="cart-link_main-nav" class="nav-link" href="{% url 'cart:page' %}">
                    <i class="fas fa-shopping-cart"></i> Корзина <span class="badge badge-secondary">{{ cart_qty }}</span>
                </a>
            </li>
        </ul>
    </div>
</nav>