apps/shop/urls.py
from django.urls import path, include

from apps.shop.views import (
    products_list,
    product_detail,
    category_products,
    search_results_view,
    cart_page,
    checkout_page,
    checkout_success_page,
    add_to_cart,
    update_cart,
    clear_cart,

    cart_api,
)


# app_name = 'products'

urlpatterns = [
    path('products/', include(([
        path('', products_list, name='list'),
        path('<int:id>/', product_detail, name='detail'),
    ], 'products'), namespace='products')),


    path('category/', include(([
        path('<slug:slug>/', category_products, name='slug'),
    ], 'category'), namespace='category')),


    path('search-results/', include(([
        path('', search_results_view, name='results'),
    ], 'search'), namespace='search')),


    # Cart
    path('cart/', include(([
        path('', cart_page, name='page'),
        path('checkout/', checkout_page, name='checkout'),
        path('checkout-success/', checkout_success_page, name='checkout-success'),
        path('add/', add_to_cart, name='add'),
        path('update/', update_cart, name='update'),
        path('clear-cart/', clear_cart, name='clear'),

        path('api/', cart_api, name='api'),
    ], 'cart'), namespace='cart')),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.core.urls')),
    path('', include('apps.pages.urls')),
    path('', include('apps.shop.urls')),
]


# if settings.DEBUG:
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'apps.core.views.error_404'

apps/shop/models.py
from django.db import models
from django.urls import reverse
from django.utils.html import mark_safe

from django.db.models.signals import pre_save, post_save, post_delete
from django.dispatch import receiver

from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill, ResizeToFit


class Categories(models.Model):
    name = models.CharField('Название категории', max_length=255)
    slug = models.SlugField('URL категории', max_length=100, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category:slug', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории товаров'


def main_image_upload_path(instance, filename):
    return f'products/{instance.sku}/{filename.lower()}'

class Products(models.Model):
    active         = models.BooleanField('Активный', default=True, help_text='Опубликован ли товар?')
    sku            = models.CharField('Артикул', max_length=50)
    name           = models.CharField('Название товара', max_length=255)
    categories     = models.ManyToManyField(Categories, verbose_name='Категории товара')
    price_discount = models.DecimalField('Цена без скидки', max_digits=8, decimal_places=2, blank=True, null=True)
    price          = models.DecimalField('Цена', max_digits=8, decimal_places=2)
    body           = models.TextField('Описание товара', blank=True, null=True)
    # main_image     = models.ImageField('Главное изображение', upload_to=main_image_upload_path, blank=True, null=True)
    main_image     = ProcessedImageField(verbose_name='Главное изображение',
                                        upload_to=main_image_upload_path,
                                        processors=[ResizeToFit(1920, 1080)],
                                        format='JPEG',
                                        options={'quality': 75},
                                        blank=True, null=True)

    main_image_thumbnail = ImageSpecField(source='main_image',
                                        # processors=[ResizeToFill(512, 512)],
                                        processors=[ResizeToFit(512, 512)],
                                        format='JPEG',
                                        options={'quality': 70})

    updated        = models.DateTimeField(auto_now=True, auto_now_add=False)

    # Thumbnail for admin
    def main_image_thumb(self):
        return mark_safe(f'<img style="width: 512px; height: auto;" src="{self.main_image.url}" alt="">')
    main_image_thumb.short_description = 'Главное изображение (thumb)'
    # END Thumbnail for admin

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


def product_image_upload_path(instance, filename):
    return f'products/{instance.product.sku}/{filename.lower()}'

class ProductsImages(models.Model):
    product = models.ForeignKey(Products, verbose_name='Товар', on_delete=models.CASCADE)
    image   = ProcessedImageField(verbose_name='Изображение',
                                upload_to=product_image_upload_path,
                                processors=[ResizeToFit(1920, 1080)],
                                format='JPEG',
                                options={'quality': 75},
                                blank=True, null=True)

    image_thumbnail = ImageSpecField(source='image',
                                    processors=[ResizeToFill(128, 100)],
                                    format='JPEG',
                                    options={'quality': 70})

    # Thumbnail for admin
    def image_thumb(self):
        return mark_safe(f'<img style="width: 386px; height: auto;" src="{self.image.url}" alt="">')
    image_thumb.short_description = 'Изображение (thumb)'
    # END Thumbnail for admin

    def __str__(self):
        return self.product.name

    class Meta:
        verbose_name = 'Изображение товара'
        verbose_name_plural = 'Изображения товаров'



# @receiver(post_save, sender=Categories)
# def lowercase_category_slug(sender, instance, created, **kwargs):
@receiver(pre_save, sender=Categories)
def lowercase_category_slug(sender, instance, **kwargs):
    instance.slug = instance.slug.lower()

apps/shop/forms.py
from django import forms


class CheckoutForm(forms.Form):
    fio      = forms.CharField(max_length=255, help_text='Укажите вашу Фамилию, Имя и Отчество')
    zip_code = forms.CharField(max_length=50, help_text="<a href=\"https://pochta.ru/post-index\" target=\"_blank\">Найти свой индекс</a>")
    address  = forms.CharField(max_length=255, help_text='Город, улица, дом, квартира')
    phone    = forms.CharField(max_length=100, help_text='Укажите в формате: +7 999 000-00-00')
    email    = forms.EmailField(max_length=200, help_text='Укажите ваш действующий email')
    message  = forms.CharField(widget=forms.Textarea,
                                max_length=1000,
                                required=False,
                                help_text='Укажите комментарий или примечание к вашему заказу')

apps/shop/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.http import JsonResponse

# from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string

from .models import Categories, Products, ProductsImages
from .forms import CheckoutForm


def products_list(request):
    products = Products.objects.filter(active=True).order_by('-updated')

    # Filters
    filter_price = request.GET.get('price')
    filter_category = request.GET.get('category')

    if filter_price and filter_price == 'asc':
        products = products.order_by('price')

    if filter_price and filter_price == 'desc':
        products = products.order_by('-price')

    if filter_category and filter_category != '':
        products = products.filter(categories__slug=filter_category)
    # END Filters

    # Pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(products, 6)
    # paginator = Paginator(products, 1)

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    # END Pagination

    context = {
        'page_title': 'Каталог товаров',
        # 'page_description': 'Описание каталога',
        'products': products,
        'categories': Categories.objects.all(),
    }
    return render(request, 'shop/products_list.html', context=context)


def product_detail(request, id):
    product = Products.objects.filter(active=True).get(id=id)
    context = {
        'page_title': product.name,
        'product': product,
        'product_images': ProductsImages.objects.filter(product=product.pk),
        'other_products': Products.objects.filter(active=True).exclude(id=product.pk).order_by('?')[:6],
    }
    return render(request, 'shop/product_detail.html', context=context)


def category_products(request, slug):
    products = Products.objects.filter(active=True, categories__slug=slug).order_by('-updated')

    # Pagination
    page = request.GET.get('page', 1)
    paginator = Paginator(products, 6)
    # paginator = Paginator(products, 1)

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    # END Pagination

    context = {
        'page_title': Categories.objects.get(slug=slug).name,
        'products': products,
    }
    return render(request, 'shop/category_products.html', context=context)


def search_results_view(request):
    search_query = request.GET.get('q')

    if search_query:
        products = Products.objects.filter(active=True, name__icontains=search_query)
        products_count = str(products.count())

        # Pagination
        page = request.GET.get('page', 1)
        paginator = Paginator(products, 6)

        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)
        # END Pagination

        context = {
            'page_title': 'Результаты поиска: ' + search_query,
            'page_description': 'найдено ' + products_count + ' результатов',
            'products': products,
        }
        return render(request, 'shop/serch_results.html', context=context)

    if not search_query:
        return redirect('/products/')


def cart_page(request):
    context = {
        'page_title': 'Корзина',
    }
    return render(request, 'shop/cart_page.html', context=context)


def checkout_page(request):
    form = CheckoutForm()

    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            # print(form.cleaned_data['fio'])
            # print(form.cleaned_data['zip_code'])
            # print(form.cleaned_data['address'])
            # print(form.cleaned_data['phone'])
            # print(form.cleaned_data['email'])
            # print(form.cleaned_data['message'])

            # Send Order email from template
            total_qty = total_price = 0

            # Calculate totals
            for item in request.session.get('cart'):
                total_qty += item['qty']
                total_price += item['price']

            context_data = {
                'fio': form.cleaned_data['fio'],
                'zip_code': form.cleaned_data['zip_code'],
                'address': form.cleaned_data['address'],
                'phone': form.cleaned_data['phone'],
                'email': form.cleaned_data['email'],
                'message': form.cleaned_data['message'],
                'cart_items': request.session.get('cart'),
                'total_qty': total_qty,
                'total_price': total_price,
            }

            html_body = render_to_string("email_templates/order.html", context_data)
            msg = EmailMultiAlternatives(subject='Ваш заказ', from_email='beautyroom37@mail.ru', to=['beautyroom37@mail.ru',])
            msg.attach_alternative(html_body, "text/html")
            msg.send()

            if request.session.get('cart'):
                del request.session['cart']
                request.session.modified = True
                return redirect('/cart/checkout-success/')

            return redirect('/cart/checkout/')

    context = {
        'page_title': 'Оформление заказа',
        'form': form,
    }
    return render(request, 'shop/checkout_page.html', context=context)


def checkout_success_page(request):
    context = {
        'page_title': 'Ваш заказ успешно оформлен!',
    }
    return render(request, 'shop/checkout_success_page.html', context=context)


def add_to_cart(request):
    if request.method == 'POST':
        # check if session cart not exist
        if not request.session.get('cart'):
            request.session['cart'] = list()

        data = {
            'sku': request.POST.get('product_sku'),
            'name': request.POST.get('product_name'),
            'price': float(request.POST.get('product_price').replace(',', '.')),
            'qty': int(request.POST.get('product_qty')),
        }

        product_in_cart = False

        # check if product alredy in cart
        if not any(d['sku'] == request.POST.get('product_sku') for d in request.session['cart']):
            product_in_cart = True
            request.session['cart'].append(data)
            request.session.modified = True

    # If is AJAX
    if request.is_ajax():
        return JsonResponse({'product_in_cart': product_in_cart})

    return redirect(request.POST.get('url_from'))


def cart_api(request):
    cart_session = request.session.get('cart')
    if cart_session:
        return JsonResponse(cart_session, safe=False)
    else:
        return JsonResponse({'cart_session': 'is not exist'})


def delete_empty_cart(request):
    if len(request.session['cart']) == 0:
        del request.session['cart']
        request.session.modified = True


# remove empty {} from cart list
def remove_empty_dicts_from_cart(request):
    while {} in request.session['cart']:
        request.session['cart'].remove({})
        request.session.modified = True


def update_cart(request):
    if request.method == 'POST':
        # Remove product from cart
        if request.POST.get('remove-item'):
            for item in request.session['cart']:
                if item['sku'] == request.POST.get('remove-item'):
                    item.clear()
                    request.session.modified = True

                    remove_empty_dicts_from_cart(request)
                    delete_empty_cart(request)

            # if cart has any products, redirect to /cart/ route
            if request.session.get('cart'):
                return redirect('/cart/')

            # if cart session is not exist, redirect to /products/
            if not request.session.get('cart'):
                return redirect('/products/')
        # Go to checkout page
        if request.POST.get('checkout'):
            return redirect('/cart/checkout/')


def clear_cart(request):
    if request.method == 'POST':
        if request.session.get('cart'):
            del request.session['cart']
            request.session.modified = True
    return redirect('/products/')

templates/shop/cart_page.html
{% extends 'base.html' %}

{% block body_classes %}{% spaceless %}
    {{ block.super }} cart-page
{% endspaceless %}{% endblock %}


{% block content %}
    {% if request.user.is_superuser %}
        {% if request.session %}
            <div class="container">
                <div style="background-color: gold; color: #333; padding: 15px;" class="mb-4">
                    {{ request.session.keys }}
                </div>
                {% if request.session.cart %}
                    <div style="background-color: #111; color: #EEE; padding: 15px;" class="mb-4">
                        {{ request.session.cart }}
                    </div>
                {% endif %}
            </div>
        {% endif %}
    {% endif %}

    <main id="main">
        {% if request.session.cart %}
            <div class="container mb-5">
                <form action="{% url 'cart:clear' %}" method="post">{% csrf_token %}
                    <button type="submit" class="btn btn-danger">
                        <i class="fas fa-ban"></i> Очистить корзину
                    </button>
                </form>
            </div>
            <div class="container">
                <form action="{% url 'cart:update' %}" method="POST">{% csrf_token %}
                    {% for cart_item in request.session.cart %}
                        <div class="row mb-3">
                            <div class="col-6 col-md-5">
                                <div class="h5">
                                    {{ cart_item.name }}
                                </div>
                                <small class="text-muted">Артикул: {{ cart_item.sku }}</small>
                            </div>
                            <div class="col-6 col-md-3 text-center">
                                {{ cart_item.price|floatformat:"-2" }} руб
                            </div>
                            <div class="col-6 col-md-3 text-center">
                                {{ cart_item.qty }} шт
                            </div>
                            <div class="col-6 col-md-1 text-center text-md-right">
                                <button class="btn btn-danger" type="submit" name="remove-item" value="{{ cart_item.sku }}" title="Удалить {{ cart_item.name }} из корзины">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </div>
                        </div>
                    {% endfor %}

                    {% include 'shop/includes/total-cart.html' %}

                    <div class="row mt-4">
                        <div class="col-0 offset-lg-7"></div>
                        <div class="col-12 col-lg-5 text-center text-lg-right">
                            <button class="btn btn-lg btn-success" type="submit" name="checkout" value="checkout">
                                <i class="fas fa-check"></i> Оформить заказ
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        {% else %}
            <div class="container text-center">
                Ваша корзина пуста =(
            </div>
        {% endif %}
    </main>
{% endblock %}

templates/shop/category_products.html
{% extends 'base.html' %}


{% block body_classes %}{% spaceless %}
    {{ block.super }} products-category
{% endspaceless %}{% endblock %}


{% block content %}
    {% if products %}
        <main id="main">
            <div class="container">
                <div class="row">
                    {% for product in products %}
                        {% include 'shop/cards/product-card.html' %}
                    {% endfor %}
                </div>
            </div>
        </main>

        {% include 'shop/includes/pagination.html' %}
    {% endif %}
{% endblock %}

templates/shop/checkout_success_page.html
{% extends 'base.html' %}

{% load widget_tweaks %}


{% block body_classes %}{% spaceless %}
    {{ block.super }} checkout-success-page
{% endspaceless %}{% endblock %}


{% block content %}
    <main id="main">
        <div class="container">
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quis maxime reprehenderit exercitationem voluptates consequuntur consectetur ad sit, amet modi nostrum at tempora vel illum odit voluptas nihil recusandae veniam obcaecati!</p>
        </div>
    </main>
{% endblock %}

templates/shop/product_detail.html
{% extends 'base.html' %}

{% block body_classes %}{% spaceless %}
    {{ block.super }} product-detail
{% endspaceless %}{% endblock %}

{% block css_libs %}
    {{ block.super }}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
{% endblock %}

{% block js_libs %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
{% endblock %}

{% block content %}
    <main id="main">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-5 mb-4 mb-lg-0">
                    <div class="product__images">
                        <div class="product__images--main">
                            {% if product.main_image %}
                                <a href="{{ product.main_image.url }}" data-fancybox="gallery-{{ product.id }}" data-caption="{{ product.name }} #1">
                                    <img src="{{ product.main_image_thumbnail.url }}" alt="{{ product.name }}">
                                </a>
                            {% else %}
                                <a href="https://via.placeholder.com/1280x768" data-fancybox="gallery-{{ product.id }}" data-caption="{{ product.name }} #1">
                                    <img src="https://via.placeholder.com/512x512" alt="">
                                </a>
                            {% endif %}
                        </div>
                        {% if product_images %}
                            <div class="product__images--thumbs-wrap">
                                {% for product_image in product_images %}
                                    <a class="product__images--thumbnail" href="{{ product_image.image.url }}" data-fancybox="gallery-{{ product.id }}" data-caption="{{ product.name }} #{{ forloop.counter }}">
                                        <img src="{{ product_image.image_thumbnail.url }}" alt="">
                                    </a>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-12 col-lg-7">
                    <div class="product__info-item">
                        <div class="mb-2">
                            <strong>Артикул:</strong> {{ product.sku }}
                        </div>
                        <div>
                            <strong>Категория:</strong> {% for category in product.categories.all %}<a href="{% url 'category:slug' slug=category.slug %}">{{ category.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}
                        </div>
                        <div class="my-3">
                            {{ product.body|safe }}
                        </div>
                        <div class="my-4">
                            {% if product.price_discount %}
                                <div class="h5 text-muted product-price__dicount">{{ product.price_discount|floatformat:"-2" }} руб</div>
                            {% endif %}
                            <div class="h4">{{ product.price|floatformat:"-2" }} руб</div>
                        </div>
                        <div class="product-add-to-cart">
                            {% include 'shop/includes/add-to-cart.html' with product_sku=product.sku product_name=product.name product_qty=1 product_price=product.price %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

    {% if other_products %}
        <section class="section-type-one">
            <div class="section-type-one__title container">
                <h2>Другие товары</h2>
            </div>
            <div class="container">
                <div class="row">
                    {% for product in other_products %}
                        {% include 'shop/cards/product-card.html' %}
                    {% endfor %}
                </div>
            </div>
        </section>
    {% endif %}

{% endblock %}

templates/shop/products_list.html
{% extends 'base.html' %}


{% block body_classes %}{% spaceless %}
    {{ block.super }} products-list
{% endspaceless %}{% endblock %}


{% block content %}
    {% include 'shop/includes/search_section.html' %}

    {% include 'shop/includes/filters-products.html' %}

    {% if products %}
        <main id="main">
            <div class="container">
                <div class="row">
                    {% for product in products %}
                        {% include 'shop/cards/product-card.html' %}
                    {% endfor %}
                </div>
            </div>
        </main>

        {% include 'shop/includes/pagination.html' %}
    {% endif %}
{% endblock %}

templates/shop/serch_results.html
{% extends 'base.html' %}

{% block meta %}
    <meta name="robots" content="noindex, nofollow">
{% endblock %}

{% block body_classes %}{% spaceless %}
    {{ block.super }} search-results
{% endspaceless %}{% endblock %}

{% block content %}
    {% include 'shop/includes/search_section.html' %}

    {% if products %}
        <main id="main">
            <div class="container">
                <div class="row">
                    {% for product in products %}
                        {% include 'shop/cards/product-card.html' %}
                    {% endfor %}
                </div>
            </div>
        </main>

        {% include 'shop/includes/pagination-search.html' %}
    {% endif %}
{% endblock %}